jb2a:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  base_servo1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_servo1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  servo2_arm1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo2_arm1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  servo4_arm2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo4_arm2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  servo5_arm3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo5_arm3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  servo6_hand_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo6_hand_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
